{
 "title": "StackStorm Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Auth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Authentication Requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Num Requests",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "st2.auth.request",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ]
      },
      {
       "alias": "Num Responses - Success (2xx)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "st2.auth.response.status",
       "query": "SELECT non_negative_derivative(sum(\"value\"), 10s) FROM \"st2.auth.response\" WHERE (\"status\" =~ /2[\\d]+/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=~", "value": "/2[\\d]+/" }
       ]
      },
      {
       "alias": "Num Responses - Errors (4-5xx)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "st2.auth.response.status",
       "query": "SELECT non_negative_derivative(sum(\"value\"), 10s) FROM \"st2.auth.response\" WHERE (\"status\" =~ /[4-9][\\d]+/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=~", "value": "/[4-9][\\d]+/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "API Responses",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Num Respones - Success (2xxx)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "st2.api.response.status",
       "query": "SELECT sum(\"value\") FROM \"st2_api_response_status\" WHERE (\"status_code\" =~ /2[\\d]+/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=~", "value": "/2[\\d]+/" }
       ]
      },
      {
       "alias": "Num Responses - Errors (4-5xxx)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "st2.api.response.status",
       "query": "SELECT non_negative_derivative(sum(\"value\"), 10s) FROM \"st2_api_response_status\" WHERE (\"status_code\" =~ /[4-9][\\d]+/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=~", "value": "/[4-9][\\d]+/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Executions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Action Executions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "st2.action.executions",
       "query": "SELECT non_negative_derivative(sum(\"value\"), 10s) FROM \"st2.action.executions\" WHERE (\"status\" = '') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        {
         "key": "status",
         "operator": "=",
         "value": "\"\""
        }
       ]
      }
     ]
    },
    {
     "title": "Action Executions Running",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "st2.action.executions",
       "query": "SELECT sum(\"value\") FROM \"st2_action_executions_running\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "running" }
       ]
      }
     ]
    },
    {
     "title": "Action Executions by Status",
     "type": "graph",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_status",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "status" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "st2.action.executions",
       "query": "SELECT non_negative_derivative(sum(\"value\"), 10s) FROM \"st2.action.executions\" WHERE (\"status\" =~ /[a-z]+/) AND $timeFilter GROUP BY time($__interval), \"status\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=~", "value": "/[a-z]+/" }
       ]
      }
     ]
    },
    {
     "title": "Action Running per Host",
     "type": "graph",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "st2.action.executions",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "running" }
       ]
      }
     ]
    },
    {
     "title": "Exections by Action",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_pack.$tag_action",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "action" ], "type": "tag" },
        { "params": [ "pack" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "st2.action",
       "query": "SELECT non_negative_derivative(sum(\"executions\"), 10s)FROM \"st2.action\" WHERE (\"action\" != '') AND $timeFilter GROUP BY time($__interval), \"pack\", \"action\" fill(null)",
       "select": [
        [
         { "params": [ "executions" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "metric_type", "operator": "=", "value": "counter" }
       ]
      }
     ]
    },
    {
     "title": "Slowest Execution Times by Action (seconds)",
     "type": "graph",
     "description": "Amount of time an action took to run, max()'d ",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_pack.$tag_action",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "pack" ], "type": "tag" },
        { "params": [ "action" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "st2.action",
       "query": "SELECT non_negative_derivative(sum(\"mean\"), 10s) FROM \"st2.action.executions\" WHERE (\"action_ref\" = 'core.local' AND \"metric_type\" = 'timing') AND $timeFilter GROUP BY time($__interval), \"action_ref\" fill(null)",
       "select": [
        [
         { "params": [ "executions_mean" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ " / 1000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "metric_type", "operator": "=", "value": "timing" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Rules and Triggers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rules Processed per Host",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "st2.rule",
       "select": [
        [
         { "params": [ "processed" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "metric_type", "operator": "=", "value": "counter" }
       ]
      }
     ]
    },
    {
     "title": "Rules Matched by Name",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Matched $tag_pack.$tag_rule",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "pack" ], "type": "tag" },
        { "params": [ "rule" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "st2.rule",
       "query": "SELECT non_negative_derivative(sum(\"matched\"), 10s) FROM \"st2.rule\" WHERE (\"metric_type\" = 'counter' AND \"pack\" != '') AND $timeFilter GROUP BY time($__interval), \"pack\", \"rule\" fill(none)",
       "select": [
        [
         { "params": [ "matched" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "metric_type", "operator": "=", "value": "counter" },
        { "condition": "AND", "key": "pack", "operator": "=", "value": "select tag value" }
       ]
      }
     ]
    },
    {
     "title": "Triggers Processed per Host",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "st2.trigger",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "metric_type", "operator": "=", "value": "counter" }
       ]
      }
     ]
    },
    {
     "title": "Triggers by Name",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Processed $tag_pack.$tag_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "pack" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "st2.trigger",
       "query": "SELECT non_negative_derivative(sum(\"value\"), 10s) FROM \"st2.rule\" WHERE (\"metric_type\" = 'counter' AND \"pack\" != '') AND $timeFilter GROUP BY time($__interval), \"pack\", \"rule\" fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "metric_type", "operator": "=", "value": "counter" },
        { "condition": "AND", "key": "flag", "operator": "=", "value": "processed" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Workflows",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Workflow Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Orquesta Workflows",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "st2.orquesta.workflow.executions",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "metric_type", "operator": "=", "value": "counter" }
       ]
      },
      {
       "alias": "Orquesta Workflow Task Actions",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "st2.orquesta.action.executions",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "metric_type", "operator": "=", "value": "counter" }
       ]
      }
     ]
    }
   ]
  }
 ]
}