---
- name: Install StackStorm Worker
  hosts: all
  environment: "{{ st2_proxy_env | default({}) }}"
  collections:
    - ansible.posix
    - community.mongodb
    - community.rabbitmq
  vars:
    st2ha_node_type: 'worker'
  roles:
    - BlueCycleOps.st2ha
    - StackStorm.st2repo
    - StackStorm.st2
    - StackStorm.nginx
    - StackStorm.st2web
    - BlueCycleOps.ssl
