---
- name: Install StackStorm Controller
  hosts: all
  environment: "{{ st2_proxy_env | default({}) }}"
  collections:
    - ansible.posix
    - community.mongodb
    - community.rabbitmq
  vars:
    st2ha_node_type: 'controller'
  roles:
    - BlueCycleOps.st2ha
    - BlueCycleOps.mongodb
    - BlueCycleOps.rabbitmq
    - BlueCycleOps.redis
    - StackStorm.st2repo
    - StackStorm.st2
    - StackStorm.nginx
    - StackStorm.st2web
    - BlueCycleOps.ssl
    - StackStorm.nodejs
    - StackStorm.st2chatops
