---
galaxy_info:
  description: Deploy StackStorm packs in an HA environment to worker nodes
  author: BlueCycleOps
  company: BlueCycleOps
  license: Apache 2.0
  min_ansible_version: 2.5
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - xenial
    - name: EL
      versions:
        - 7
        - 8
  galaxy_tags:
    - system
    - stackstorm
    - st2
    - automation
    - remediation
    - devops
    - ha
    - packs
    - deploy
