{
 "title": "StackStorm",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "st2interval",
    "label": "Interval",
    "query": "10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Action Executions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "st2.action.executions",
     "query": "SELECT sum(\"value\") FROM \"st2.action.executions\" WHERE (\"status\" = '') AND $timeFilter GROUP BY time($st2interval) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Actions Running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_host sum",
     "groupBy": [
      { "params": [ "$st2interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "st2.action.executions",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "$st2interval" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "running" }
     ]
    }
   ]
  },
  {
   "title": "Auth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Authentication Requests",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Num Requests",
       "groupBy": [
        { "params": [ "$st2interval" ], "type": "time" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "st2.auth.request",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "Num Responses - Success (2xx)",
       "groupBy": [
        { "params": [ "$st2interval" ], "type": "time" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "st2.auth.response.status",
       "query": "SELECT non_negative_derivative(sum(\"value\"), 10s) FROM \"st2.auth.response\" WHERE (\"status\" =~ /2[\\d]+/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=~", "value": "/2[\\d]+/" }
       ]
      },
      {
       "alias": "Num Responses - Errors (4-5xx)",
       "groupBy": [
        { "params": [ "$st2interval" ], "type": "time" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "st2.auth.response.status",
       "query": "SELECT non_negative_derivative(sum(\"value\"), 10s) FROM \"st2.auth.response\" WHERE (\"status\" =~ /[4-9][\\d]+/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=~", "value": "/[4-9][\\d]+/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "API Responses",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Num Respones - Success (2xxx)",
       "groupBy": [
        { "params": [ "$st2interval" ], "type": "time" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "st2.api.response.status",
       "query": "SELECT sum(\"value\") FROM \"st2_api_response_status\" WHERE (\"status_code\" =~ /2[\\d]+/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=~", "value": "/2[\\d]+/" }
       ]
      },
      {
       "alias": "Num Responses - Errors (4-5xxx)",
       "groupBy": [
        { "params": [ "$st2interval" ], "type": "time" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "st2.api.response.status",
       "query": "SELECT non_negative_derivative(sum(\"value\"), 10s) FROM \"st2_api_response_status\" WHERE (\"status_code\" =~ /[4-9][\\d]+/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=~", "value": "/[4-9][\\d]+/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Executions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Action Executions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Executions",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "st2.action.executions",
       "query": "SELECT sum(\"value\") FROM \"st2.action.executions\" WHERE (\"status\" = '') AND $timeFilter GROUP BY time($st2interval) fill(0)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        {
         "key": "status",
         "operator": "=",
         "value": "\"\""
        }
       ]
      }
     ]
    },
    {
     "title": "Action Executions Running",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "running",
       "groupBy": [
        { "params": [ "$st2interval" ], "type": "time" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "st2.action.executions",
       "query": "SELECT sum(\"value\") FROM \"st2_action_executions_running\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "$st2interval" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "running" }
       ]
      }
     ]
    },
    {
     "title": "Action Executions by Status",
     "type": "graph",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_status",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "status" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "st2.action.executions",
       "query": "SELECT non_negative_derivative(last(\"value\"), $st2interval) FROM \"st2.action.executions\" WHERE (\"status\" =~ /[a-z]+/) AND $timeFilter GROUP BY time($st2interval), \"status\" fill(0)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=~", "value": "/[a-z]+/" }
       ]
      }
     ]
    },
    {
     "title": "Action Running per Host",
     "type": "graph",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$st2interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "st2.action.executions",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "$st2interval" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "running" }
       ]
      }
     ]
    },
    {
     "title": "Exections by Action",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_pack.$tag_action",
       "groupBy": [
        { "params": [ "$st2interval" ], "type": "time" },
        { "params": [ "action" ], "type": "tag" },
        { "params": [ "pack" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "st2.action",
       "query": "SELECT last(\"executions\") FROM \"st2.action\" WHERE (\"metric_type\" = 'counter') AND $timeFilter GROUP BY time($__interval), \"action\", \"pack\" fill(0)",
       "select": [
        [
         { "params": [ "executions" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "metric_type", "operator": "=", "value": "counter" }
       ]
      }
     ]
    },
    {
     "title": "Slowest Execution Times by Action (seconds)",
     "type": "graph",
     "description": "Amount of time an action took to run, max()'d ",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_pack.$tag_action",
       "groupBy": [
        { "params": [ "$st2interval" ], "type": "time" },
        { "params": [ "pack" ], "type": "tag" },
        { "params": [ "action" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "st2.action",
       "query": "SELECT non_negative_derivative(sum(\"mean\"), 10s) FROM \"st2.action.executions\" WHERE (\"action_ref\" = 'core.local' AND \"metric_type\" = 'timing') AND $timeFilter GROUP BY time($__interval), \"action_ref\" fill(null)",
       "select": [
        [
         { "params": [ "executions_mean" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ " / 1000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "metric_type", "operator": "=", "value": "timing" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Rules and Triggers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rules Processed per Host",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$st2interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "st2.rule",
       "select": [
        [
         { "params": [ "processed" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "metric_type", "operator": "=", "value": "counter" }
       ]
      }
     ]
    },
    {
     "title": "Rules Matched by Name",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Matched $tag_pack.$tag_rule",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "pack" ], "type": "tag" },
        { "params": [ "rule" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "st2.rule",
       "query": "SELECT last(\"matched\") FROM \"st2.rule\" WHERE (\"metric_type\" = 'counter' AND \"pack\" != '') AND $timeFilter GROUP BY time($st2interval), \"pack\", \"rule\" fill(0)",
       "select": [
        [
         { "params": [ "matched" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "metric_type", "operator": "=", "value": "counter" },
        { "condition": "AND", "key": "pack", "operator": "=", "value": "select tag value" }
       ]
      }
     ]
    },
    {
     "title": "Triggers Processed per Host",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$st2interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "st2.trigger",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "metric_type", "operator": "=", "value": "counter" }
       ]
      }
     ]
    },
    {
     "title": "Triggers by Name",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Processed $tag_pack.$tag_name",
       "groupBy": [
        { "params": [ "$st2interval" ], "type": "time" },
        { "params": [ "pack" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "st2.trigger",
       "query": "SELECT non_negative_derivative(sum(\"value\"), 10s) FROM \"st2.rule\" WHERE (\"metric_type\" = 'counter' AND \"pack\" != '') AND $timeFilter GROUP BY time($__interval), \"pack\", \"rule\" fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "metric_type", "operator": "=", "value": "counter" },
        { "condition": "AND", "key": "flag", "operator": "=", "value": "processed" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Workflows",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Workflow Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Orquesta Workflows",
       "groupBy": [
        { "params": [ "$st2interval" ], "type": "time" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "st2.orquesta.workflow.executions",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "metric_type", "operator": "=", "value": "counter" }
       ]
      },
      {
       "alias": "Orquesta Workflow Task Actions",
       "groupBy": [
        { "params": [ "$st2interval" ], "type": "time" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "st2.orquesta.action.executions",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "metric_type", "operator": "=", "value": "counter" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Services - st2actionrunner",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "st2actionrunner CPU Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$st2interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "pattern" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "procstat",
       "select": [
        [
         { "params": [ "cpu_usage" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "pattern", "operator": "=", "value": "st2actionrunner" }
       ]
      }
     ]
    },
    {
     "title": "st2actionrunner Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$st2interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "pattern" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "procstat",
       "select": [
        [
         { "params": [ "memory_usage" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "pattern", "operator": "=", "value": "st2actionrunner" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Services - st2api",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "st2api CPU Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$st2interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "pattern" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "procstat",
       "select": [
        [
         { "params": [ "cpu_usage" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "pattern", "operator": "=", "value": "st2api" }
       ]
      }
     ]
    },
    {
     "title": "st2api Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$st2interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "pattern" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "procstat",
       "select": [
        [
         { "params": [ "memory_usage" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "pattern", "operator": "=", "value": "st2api" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Services - st2auth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "st2auth CPU Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$st2interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "pattern" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "procstat",
       "select": [
        [
         { "params": [ "cpu_usage" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "pattern", "operator": "=", "value": "st2auth" }
       ]
      }
     ]
    },
    {
     "title": "st2auth Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$st2interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "pattern" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "procstat",
       "select": [
        [
         { "params": [ "memory_usage" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "pattern", "operator": "=", "value": "st2auth" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Services - st2garbagecollector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "st2garbagecollector CPU Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$st2interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "pattern" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "procstat",
       "select": [
        [
         { "params": [ "cpu_usage" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "pattern", "operator": "=", "value": "st2garbagecollector" }
       ]
      }
     ]
    },
    {
     "title": "st2garbagecollector Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$st2interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "pattern" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "procstat",
       "select": [
        [
         { "params": [ "memory_usage" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "pattern", "operator": "=", "value": "st2garbagecollector" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Services - st2notifier",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "st2notifier CPU Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$st2interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "pattern" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "procstat",
       "select": [
        [
         { "params": [ "cpu_usage" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "pattern", "operator": "=", "value": "st2notifier" }
       ]
      }
     ]
    },
    {
     "title": "st2notifier Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$st2interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "pattern" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "procstat",
       "select": [
        [
         { "params": [ "memory_usage" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "pattern", "operator": "=", "value": "st2notifier" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Services - st2rulesengine",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "st2rulesengine CPU Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$st2interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "pattern" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "procstat",
       "select": [
        [
         { "params": [ "cpu_usage" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "pattern", "operator": "=", "value": "st2rulesengine" }
       ]
      }
     ]
    },
    {
     "title": "st2rulesengine Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$st2interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "pattern" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "procstat",
       "select": [
        [
         { "params": [ "memory_usage" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "pattern", "operator": "=", "value": "st2rulesengine" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Services - st2scheduler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "st2scheduler CPU Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$st2interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "pattern" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "procstat",
       "select": [
        [
         { "params": [ "cpu_usage" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "pattern", "operator": "=", "value": "st2scheduler" }
       ]
      }
     ]
    },
    {
     "title": "st2scheduler Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$st2interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "pattern" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "procstat",
       "select": [
        [
         { "params": [ "memory_usage" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "pattern", "operator": "=", "value": "st2scheduler" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Services - st2sensorcontainer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "st2sensorcontainer CPU Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$st2interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "pattern" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "procstat",
       "select": [
        [
         { "params": [ "cpu_usage" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "pattern", "operator": "=", "value": "st2sensorcontainer" }
       ]
      }
     ]
    },
    {
     "title": "st2sensorcontainer Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$st2interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "pattern" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "procstat",
       "select": [
        [
         { "params": [ "memory_usage" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "pattern", "operator": "=", "value": "st2scheduler" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Services - st2stream",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "st2stream CPU Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$st2interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "pattern" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "procstat",
       "select": [
        [
         { "params": [ "cpu_usage" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "pattern", "operator": "=", "value": "st2stream" }
       ]
      }
     ]
    },
    {
     "title": "st2stream Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$st2interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "pattern" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "procstat",
       "select": [
        [
         { "params": [ "memory_usage" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "pattern", "operator": "=", "value": "st2stream" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Services - st2timersengine",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "st2timersengine CPU Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$st2interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "pattern" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "procstat",
       "select": [
        [
         { "params": [ "cpu_usage" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "pattern", "operator": "=", "value": "st2timersengine" }
       ]
      }
     ]
    },
    {
     "title": "st2timersengine Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$st2interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "pattern" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "procstat",
       "select": [
        [
         { "params": [ "memory_usage" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "pattern", "operator": "=", "value": "st2stream" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Services - st2workflowengine",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "st2workflowengine CPU Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$st2interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "pattern" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "procstat",
       "select": [
        [
         { "params": [ "cpu_usage" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "pattern", "operator": "=", "value": "st2workflowengine" }
       ]
      }
     ]
    },
    {
     "title": "st2workflowengine Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$st2interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "pattern" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "procstat",
       "select": [
        [
         { "params": [ "memory_usage" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "pattern", "operator": "=", "value": "st2workflowengine" }
       ]
      }
     ]
    }
   ]
  }
 ]
}