---

- name: Prepare StackStorm Controller variables
  set_fact:
    mongodb_admin_pwd: "{{ st2ha_mongodb_password }}"
    mongodb_users:
      - db: "{{ st2ha_mongodb_database }}"
        user: "{{ st2ha_mongodb_username }}"
        pwd: "{{ st2ha_mongodb_password }}"
        roles: "readWrite,dbAdmin"
    rabbitmq_vhosts:
      - "{{ st2ha_rabbitmq_vhost }}"
    rabbitmq_users:
      - user: "{{ st2ha_rabbitmq_username }}"
        password: "{{ st2ha_rabbitmq_password }}"
        # setup this user for RabbitMQ telegraf monitoring
        # https://www.rabbitmq.com/management.html#permissions
        # CSV string here
        tags: administrator
        permissions:
          - vhost: "{{ st2ha_rabbitmq_vhost }}"
            configure_priv: .*
            read_priv: .*
            write_priv: .*
    redis_bind_interface: 0.0.0.0
    redis_requirepass: "{{ st2ha_redis_password }}"
    st2_config:
      coordination:
        url: "redis://:{{ st2ha_redis_password }}@{{ st2ha_controller_host }}"
      database:
        host: "{{ st2ha_controller_host }}"
        username: "{{ st2ha_mongodb_username }}"
        password: "{{ st2ha_mongodb_password }}"
        db_name: "{{ st2ha_mongodb_database }}"
      garbagecollector:
        action_executions_output_ttl: "{{ st2ha_garbagecollector_action_executions_output_ttl }}"
        action_executions_ttl: "{{ st2ha_garbagecollector_action_executions_ttl }}"
        trigger_instances_ttl: "{{ st2ha_garbagecollector_trigger_instances_ttl }}"
        purge_inquiries: True
      messaging:
        url: "amqp://{{ st2ha_rabbitmq_username }}:{{ st2ha_rabbitmq_password }}@{{ st2ha_controller_host }}:5672/"
      metrics:
        driver: statsd
        # telegraf is configured as a statsd server, it will receive the statsd metrics
        # and push them to influxdb
        host: 127.0.0.1
        port: 8125
      timersengine:
        enable: 'True'
        # for whatever reason, you have to use this timezone, sorry it's a bug
        local_timezone: 'America/Los_Angeles'
    # we'll install the st2 pack later, put them in st2ha_packs
    st2_packs: []
    st2_python_packages:
      - redis
    # only run the following service (and st2chatops, but that is controlled via a role)
    # - st2notifier can only one run of these
    # - st2auth needed for st2chatops Ansible role in order to generate an API key
    # - st2api needed for st2chatops Ansible role in order to generate an API key
    # - st2garbagecollector cleans up the database, purging old executions and triggers
    #                      we run this on the controller because that is where the database lives
    # - st2timersengine can only run one of these
    st2_services:
      - st2api
      - st2auth
      - st2garbagecollector
      - st2notifier
      - st2timersengine
    st2_services_versioned: {}
    st2web_nginx_config: "{{ lookup('template', '../templates/nginx_controller.conf.j2') }}"
  tags: st2ha, config

