---

- name: Make local directory for st2ha files
  delegate_to: localhost
  file:
    path: files
    state: directory
  when: not st2_datastore_key

- name: Generate st2ha encryption key
  delegate_to: localhost
  shell:
    cmd: "source virtualenv/bin/activate && st2-generate-symmetric-crypto-key --key-path {{ st2ha_datastore_key_path }}"
    chdir: "{{ lookup('env', 'PWD') }}"
  args:
    creates: "{{ st2ha_datastore_key_path }}"
  when: not st2_datastore_key

- name: "Read st2_datastore_key from {{ st2ha_datastore_key_path }}"
  delegate_to: localhost
  set_fact:
    st2_datastore_key: "{{ lookup('file', st2ha_datastore_key_path) }}"
  when: not st2_datastore_key
