---

- name: Setup Telegraf varaibles for StackStorm Controller
  include_tasks: telegraf_controller.yml
  when: st2ha_node_type == 'controller'

- name: Setup Telegraf varaibles for StackStorm Worker
  include_tasks: telegraf_worker.yml
  when: st2ha_node_type == 'worker'

- name: Set Telegraf as the group for /var/log/nginx so it can read log files
  file:
    path: /var/log/nginx
    owner: nginx
    group: telegraf
    recurse: true
  become: true

- name: Ensure nginx logrotate uses telegraf as the group so it can read log files
  lineinfile:
    path: /etc/logrotate.d/nginx
    regexp: '^    create '
    line: '    create 0664 nginx telegraf'
  become: true

- include_role:
    name: dj-wasabi.telegraf
    apply:
      become: true
