---

- set_fact:
    telegraf_agent_output:
      - type: influxdb
        config:
          - urls = ["http://{{ st2ha_influxdb_host }}:8086"]
          - database = "{{ st2ha_influxdb_database }}"
          - username = "{{ st2ha_influxdb_telegraf_username }}"
          - password = "{{ st2ha_influxdb_telegraf_password }}"
    telegraf_plugins_default:
      - plugin: cpu
        config:
          - percpu = true
          - totalcpu = true
          - fielddrop = ["time_*"]
      - plugin: conntrack
        config:
          - files = ["ip_conntrack_count","ip_conntrack_max", "nf_conntrack_count","nf_conntrack_max"]
          - dirs = ["/proc/sys/net/ipv4/netfilter","/proc/sys/net/netfilter"]
      - plugin: disk
      - plugin: diskio
      - plugin: kernel
      - plugin: mem
      - plugin: processes
      - plugin: swap
      - plugin: system
      - plugin: net
      - plugin: netstat
      - plugin: nstat
      - plugin: interrupts
      - plugin: linux_sysctl_fs
      - plugin: internal
        config:
          - collect_memstats = true
      - plugin: statsd
        config:
          - protocol = "udp"
          - service_address = ":8125"
          - metric_separator = '.'
          ## Reset gauges every interval (default=true)
          - delete_gauges = false
          ## Reset counters every interval (default=true)
          - delete_counters = false
          ## Reset sets every interval (default=true)
          - delete_sets = false
          ## Reset timings & histograms every interval (default=true)
          - delete_timings = true
          # Tell telegraf to pull out the status code from these metrics names and
          # assign it to the status_code field on the metric
          - templates = ["st2.action.executions.* measurement.measurement.measurement.status", "st2.action.*.*.executions measurement.measurement.pack.action.field", "st2.amqp.pool_publisher.publish_with_retries.* measurement.measurement.measurement.measurement.field", "st2.amqp.publish.* measurement.measurement.measurement.field", "st2.*.request.method.* measurement.measurement.measurement.measurement.method", "st2.*.request.path.* measurement.measurement.measurement.measurement.path", "st2.*.response.status.* measurement.measurement.measurement.measurement.status", "st2.trigger.*.*.processed measurement.measurement.pack.name.flag", "st2.trigger.*.*.*.*.processed measurement.measurement.pack.name.name.name.flag", "st2.notifier.* measurement.measurement.notifier", "st2.orquesta.*.*, measurement.measurement.field.measurement" ]



# TODO
# - MongoDB
# - RabbitMQ
# - nginx
# - StackStorm/statsd
