---

- set_fact:
    telegraf_agent_version: 1.17.0
    telegraf_agent_output:
      - type: influxdb
        config:
          - urls = ["http://{{ st2ha_influxdb_host }}:8086"]
          - database = "{{ st2ha_influxdb_database }}"
          - username = "{{ st2ha_influxdb_telegraf_username }}"
          - password = "{{ st2ha_influxdb_telegraf_password }}"
          - precision = "1us"
    telegraf_global_tags:
      - tag_name: st2role
        tag_value: worker
    telegraf_plugins_default:
      - plugin: cpu
        config:
          - percpu = true
          - totalcpu = true
          - fielddrop = ["time_*"]
      # firewalld isn't enabled in EC2 so it causes this to fail
      # - plugin: conntrack
      #   config:
      #     - files = ["ip_conntrack_count","ip_conntrack_max", "nf_conntrack_count","nf_conntrack_max"]
      #     - dirs = ["/proc/sys/net/ipv4/netfilter","/proc/sys/net/netfilter"]
      - plugin: disk
      - plugin: diskio
      - plugin: kernel
      - plugin: mem
      - plugin: processes
      - plugin: swap
      - plugin: system
      - plugin: net
      - plugin: netstat
      - plugin: nstat
      - plugin: interrupts
      - plugin: linux_sysctl_fs
      - plugin: systemd_units
      - plugin: internal
        config:
          - collect_memstats = true
      - plugin: statsd
        config:
          - protocol = "udp"
          - service_address = ":8125"
          - metric_separator = '.'
          ## Reset gauges every interval (default=true)
          - delete_gauges = false
          ## Reset counters every interval (default=true)
          - delete_counters = true
          ## Reset sets every interval (default=true)
          - delete_sets = false
          ## Reset timings & histograms every interval (default=true)
          - delete_timings = true
          # Tell telegraf to pull out the status code from these metrics names and
          # assign it to the status_code field on the metric
          - templates = ["st2.action.executions.* measurement.measurement.measurement.status", "st2.action.*.*.executions measurement.measurement.pack.action.field", "st2.amqp.pool_publisher.publish_with_retries.* measurement.measurement.measurement.measurement.field", "st2.amqp.publish.* measurement.measurement.measurement.field", "st2.*.request.method.* measurement.measurement.measurement.measurement.method", "st2.*.request.path.* measurement.measurement.measurement.measurement.path", "st2.*.response.status.* measurement.measurement.measurement.measurement.status", "st2.rule.*.*.* measurement.measurement.pack.rule.field", "st2.rule.* measurement.measurement.field", "st2.trigger.*.*.processed measurement.measurement.pack.name.flag", "st2.trigger.*.*.processed measurement.measurement.pack.name.flag", "st2.trigger.*.*.*.processed measurement.measurement.pack.name.name.flag", "st2.trigger.*.*.*.*.processed measurement.measurement.pack.name.name.name.flag", "st2.notifier.* measurement.measurement.notifier", "st2.orquesta.*.*, measurement.measurement.field.measurement" ]
      - plugin: nginx
        config:
          - urls = ["https://localhost/basic_status"]
          - insecure_skip_verify = true
      - plugin: logparser
        config:
          - files = ["/var/log/nginx/access.log", "/var/log/nginx/ssl-st2webui.access.log", "/var/log/nginx/st2webui.access.log"]
          - from_beginning = true
          - name_override = "nginx_access_log"
          - "[inputs.logparser.grok]"
          - '  patterns = ["%{COMBINED_LOG_FORMAT}"]'

# get status of all the st2 services
- set_fact:
    telegraf_plugins_default: "{{ telegraf_plugins_default + [ {\"plugin\": \"procstat\", \"config\": [\"pattern = \" + '\"' + item + '\"' + \"\"] } ] }}"
  with_items: "{{ st2_services }}"

# get all of the running st2sensor instances
- set_fact:
    telegraf_plugins_default: "{{ telegraf_plugins_default + [ {\"plugin\": \"procstat\", \"config\": [\"pattern = \" + '\"sensor_wrapper.py\"', \"cmdline_tag = true\"] } ] }}"
  
- debug:
    msg: "telegraf plugin defaults = {{ telegraf_plugins_default }}"

- name: Ensure /etc/telegraf has correct permissions
  become: yes
  file:
    path: /etc/telegraf
    state: directory
    mode: 0755
    owner: telegraf
    group: telegraf
    
# save credentials so telegraf can call st2 CLI/API to get data
- name: Create Telegraf st2 CLI configuration directory
  become: yes
  file:
    path: /etc/telegraf/.st2
    state: directory
    mode: 0700
    owner: telegraf
    group: telegraf

- name: Save st2 credentials in Telegraf CLI configuration file
  become: yes
  blockinfile:
    dest: /etc/telegraf/.st2/config
    create: yes
    mode: 0600
    owner: telegraf
    group: telegraf
    block: |
      [credentials]
      username = {{ st2_auth_username }}
      password = {{ st2_auth_password }}

# copy sensor metrics script
- name: Copy telegraf st2 metrics scripts
  become: yes
  copy:
    src: "{{ st2ha_telegraf_scripts_src }}"
    dest: "{{ st2ha_telegraf_scripts_dest }}"
    mode: 0700
    owner: telegraf
    group: telegraf

# execute custom st2 telegraf scripts
- set_fact:
    telegraf_plugins_default: "{{ telegraf_plugins_default + [ {\"plugin\": \"exec\", \"config\": [\"commands = [\" + '\"' + st2ha_telegraf_scripts_dest + '/*\"]', \"data_format = \" + '\"influx\"'] } ] }}"
