---
galaxy_info:
  description: Install SSL/TLS CAs and Certificates
  author: BlueCycleOps
  company: BlueCycleOps
  license: Apache
  min_ansible_version: 2.5
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - xenial
    - name: EL
      versions:
        - 7
        - 8
  galaxy_tags:
    - system
    - ssl
